/**
 * @file src/core/fileProcessor.js
 * @description Handles the processing of a single YAML file: reading, parsing,
 * generating test code, and writing (or simulating) the .test.js output.
 * @author Your Name/AI Assistant
 * @license MIT
 */

const fs = require("fs");
const path = require("path");
const yaml = require("js-yaml");
const { log, LOG_LEVELS } = require("../utils/logger"); // Import logger
const { generateTestCode } = require("./testGenerator"); // Import test generator

/**
 * Processes a single YAML file.
 * Reads the YAML content, parses it, generates Jest-compatible test code,
 * and then writes the generated code to a `.test.js` file in the same directory
 * as the source YAML. Supports dry run mode.
 *
 * @param {string} yamlFilePath - The full path to the YAML file to process.
 * @param {object} cliConfig - The consolidated configuration object for the CLI,
 * containing properties like `testKeyword`, `isDryRun`.
 */
function processFile(yamlFilePath, cliConfig) {
  try {
    log(`Processing file: ${yamlFilePath}`, LOG_LEVELS.DEBUG);
    const fileContent = fs.readFileSync(yamlFilePath, "utf8");
    const parsedYaml = yaml.load(fileContent);

    if (typeof parsedYaml !== "object" || parsedYaml === null) {
      log(
        `⚠️ Warning: YAML file '${yamlFilePath}' is empty or does not contain a valid object structure. Skipping.`,
        LOG_LEVELS.WARN
      );
      return;
    }

    const generatedCode = generateTestCode(parsedYaml, cliConfig.testKeyword);

    const dirName = path.dirname(yamlFilePath);
    const baseName = path.basename(yamlFilePath, path.extname(yamlFilePath));
    const outputFileName = `${baseName}.test.js`;
    const outputFilePath = path.join(dirName, outputFileName);

    const fileHeader = `/**
 * @file ${outputFileName}
 * @description Generated test file from ${path.basename(yamlFilePath)}.
 * This file contains Jest 'describe' and '${
   cliConfig.testKeyword
 }' blocks based on your YAML structure.
 * Please fill in the actual test logic.
 * @generated by yaml-to-test-cli
 */\n\n`;

    if (cliConfig.isDryRun) {
      log(
        `Would generate test file: ${outputFilePath} (Dry Run)`,
        LOG_LEVELS.INFO
      );
      log(
        `--- Content Preview for ${outputFilePath} ---\n${fileHeader}${generatedCode}\n--- End Preview ---`,
        LOG_LEVELS.DEBUG
      );
    } else {
      fs.writeFileSync(outputFilePath, fileHeader + generatedCode, "utf8");
      log(
        `✅ Successfully generated test file: ${outputFilePath}`,
        LOG_LEVELS.INFO
      );
    }
  } catch (error) {
    log(
      `❌ Error processing file '${yamlFilePath}': ${error.message}`,
      LOG_LEVELS.ERROR
    );
  }
}

module.exports = {
  processFile,
};
